spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.0.76:3306/carrot
    username: "sehyun"
    password: "0000"
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        use-new-id-generator-mappings: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    properties:
#      hibernate:
#        ejb:
#          interceptor: com.carrot.back.config.CustomAuditorAware
#        format_sql: true
security:
  oauth2:
    client-id: dU7pnJEZJqJCYlRVyF3hJdaVQbtV5umA
    client-key: fr7nhIfIwabINfJVNPz8O2NojaNXDvBEu4J6t0t8HQfYKpDC9NHPpVe3IcGOEiyI
  user:
    name: "user"
    password: "0000"
server:
  port: 8081
springdoc:
  swagger-ui:
    oauth:
      client-id: dU7pnJEZJqJCYlRVyF3hJdaVQbtV5umA
      client-secret: fr7nhIfIwabINfJVNPz8O2NojaNXDvBEu4J6t0t8HQfYKpDC9NHPpVe3IcGOEiyI
jwt:
  secret: "a29f08e43f0c6790b43cbec33b4e140db4f918e0dc8320a7a9decbd8461f329d"
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG